### ISSUE TITLE
Manipulator initial position altered after changing from a position_controllers/JointTrajectoryController to a effort_controllers/JointTrajectoryController

### ISSUE THREAD

**Issue by znbrito** [znbrito/Brito-thesis-Robotis-Manipulator-H-path-planning#3]
Hi, I am currently on ROS Kinetic, working on the integration of a Husky and a Robotis Manipulator-H. Right now I have the manipulator working with MoveIt! while standing fixed on top of a Husky robot. First of all I was having a problem which was the fact that when I moved the Husky robot (for example, with the teleop keyboard), his dynamics were not correct, i. .e, the front wheels would lift up when I moved him forward and the back wheels would also lift up If I moved backwards. I research about the possible reasons why this was happening and via this link:

http://answers.gazebosim.org/question/15045/why-my-model-seems-to-defy-the-gravity-and-seems-to-be-grabbed-from-the-top-when-moving/#18851

I found out that the fact that I was using a position_controllers/JointTrajectoryController to control the manipulator (via MoveIt!) was afecting my robot's dynamics. The solution was changing this controller to a effort_controllers/JointTrajectoryController, which made it possible to move my robot around normally. The only problem is that now, the initial position of the manipulator is a bit odd. The following images show the normal position of the manipulator (when using a position_controllers/JointTrajectoryController) and the position of the manipulator when using a effort_controllers/JointTrajectoryController:

Normal position:

![normal_position](https://user-images.githubusercontent.com/17012048/38023773-0dc106de-327b-11e8-8b11-197556a4eaa4.png)

Altered position:

![altered_position](https://user-images.githubusercontent.com/17012048/38023837-2d723ee4-327b-11e8-92e5-eeb4001bccb6.png)

Besides this initial position problem, path planning has equally good (or even perfect) results when using both controller types. Has this initial position any side effect in my system/manipulator/simulation?

@v4hn or @davetcoleman can you please help me?
Thanks in advance!

**Comment by v4hn** [comment]
Welcome to a world with gravity.
If your controllers don't manage to move their joints to their target positions,
it is because they can not/are not configured to apply enough force to overcome gravity.
You can have this problem just as well on a real robot.
If you don't see it there, tune your pid controller parameters to fit the real behavior.

Side note, we are not your tutor.
Feel free to highlight MoveIt maintainers if you find or suspect problems with MoveIt,
but otherwise we probably just won't respond.

**Comment by znbrito** [comment]
Hi @v4hn, thanks for your quick response.
Yes, I understand that and it makes perfect sense to me. However, If my controllers aren't well tuned, why can I achieve the same results I get when I plan using a position_controllers/JointTrajectoryController? That's what is really confusing to me because, besides the initial state, all other planned states (poses and orientation) can be perfectly achieved.

And yes, you are right! I thought you were also MoveIt! mantainers since I think I remember seeing you answering questions related to MoveIt! but I think you are just like ROS mantainers, right? Do you know who can I highlight to help me with future MoveIt! problems? 
Thanks a lot!

**Comment by v4hn** [comment]
I am a MoveIt maintainer.
My point was that if your `gazebo_ros_control` based controllers do not behave nicely, this has nothing to do with MoveIt.
If you suspect a bug in the controllers or the interaction with gazebo, file an issue there.
Don't just file an issue in your own repository highlighting random maintainers.
They tend not to be interested in your particular project.

**Comment by znbrito** [comment]
Ok, I opened a new issue in the gazebo answers website: http://answers.gazebosim.org/question/18873/manipulator-initial-position-altered-after-changing-from-a-position_controllersjointtrajectorycontroller-to-a/.

The only reason why I filed an issue in my repository is the fact that I don't know how to create issues outside of my repository, and for that I am sorry. Thanks for the help anyways!
